xgboost:
  n_estimators:  # Ağaç sayısı, modelin kaç tane karar ağacı oluşturacağını belirler.
    - 100
    - 200

  max_depth:  # Her bir karar ağacının maksimum derinliği. Derinlik arttıkça model daha karmaşık olur.
    - 3
    - 5
    - 7

  learning_rate:  # Öğrenme oranı, her iterasyonda ağırlık güncellemesinin büyüklüğünü belirler. Küçük değerler daha yavaş öğrenmeyi sağlar.
    - 0.01
    - 0.05
    - 0.1
    - 0.2

  subsample:  # Her iterasyonda kullanılacak örnekleme oranı. Aşırı öğrenmeyi (overfitting) önlemek için kullanılır.
    - 0.8  # %80 veri ile eğitim yap
    - 0.10  # %10 veri ile eğitim yap (muhtemelen çok düşük ve öğrenme kötü olabilir)

  