artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/api/v1/datasets/download/zkankurukavak/satslar-zkan  # Veri kaynağının URL'si
  local_data_file: artifacts/data_ingestion/data.zip  # İndirilen veri dosyasının kaydedileceği yer
  unzip_dir: artifacts/data_ingestion  # Zip dosyasının açılacağı dizin

data_validation: 
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/satslar.csv  # Zipten çıkarılan CSV dosyasının yolu
  STATUS_FILE: artifacts/data_validation/status.txt  # Doğrulama durumu hakkında bilgi


data_transformation:
  root_dir: artifacts/data_transformation/
  data_path: artifacts/data_ingestion/satslar.csv
  transformed_data_path: artifacts/data_transformation/
  train_data_path: artifacts/data_transformation/train_data.csv
  test_data_path: artifacts/data_transformation/test_data.csv


model_trainer:
  root_dir: "artifacts/model_trainer"          # Modelin kaydedileceği dizin
  train_data_path: "artifacts/data_transformation/train_data.csv"   # Eğitim verisi yolu
  test_data_path: "artifacts/data_transformation/test_data.csv"     # Test verisi yolu
  model_name: "xgboost_model.pkl"              # Modelin adı
  grid_search: true                            # Grid search uygulanacak mı?
  scoring_metric: "accuracy"                  # Skor metrici, doğruluk için "accuracy" kullanılabilir
  test_size: 0.2                              # Test seti boyutu, genellikle 0.2 ya da 0.3 kullanılır
  random_state: 42                            # Rastgelelikin kontrolü, sabit bir değer verilmesi iyi bir uygulamadır
  target_column: "target"                     # Hedef değişkenin adı         # Hedef değişkenin adı