artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/api/v1/datasets/download/zkankurukavak/satslar-zkan  # Veri kaynağının URL'si
  local_data_file: artifacts/data_ingestion/data.zip  # İndirilen veri dosyasının kaydedileceği yer
  unzip_dir: artifacts/data_ingestion  # Zip dosyasının açılacağı dizin

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/satslar.csv  # Zipten çıkarılan CSV dosyasının yolu
  STATUS_FILE: artifacts/data_validation/status.txt  # Doğrulama durumu hakkında bilgi

data_transformation:
  root_dir: artifacts/data_transformation/
  data_path: artifacts/data_ingestion/satslar.csv  # Doğru dosya yolunu belirledim
  transformed_data_path: artifacts/data_transformation/transformed_data.csv  # Dönüştürülmüş veri için doğru yol

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv  # Eğitim verisinin kaydedileceği yol
  test_data_path: artifacts/data_transformation/test.csv  # Test verisinin kaydedileceği yol
  model_name: "xgboost"  # Kullanılacak model türü
  model_save_path: artifacts/model_trainer/model.joblib  # Eğitilen modelin kaydedileceği yol
  grid_search: True  # GridSearch uygulanacak mı?
  scoring_metric: "neg_mean_squared_error"  # Değerlendirme metrikleri